baseURL = 'https://hamcode.net/'
languageCode = 'en-us'
title = 'HamCode'
theme = 'PaperMod'

[services.googleAnalytics]
  ID = "G-PVD8JLP4WW"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'dracula'
    lineNos = false
    lineNumbersInTable = false
    noClasses = true

[params]
  description = "Welcome to HamCode"
  author = "Hamid"
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  comments = true
  defaultTheme = "light"
  disableThemeToggle = true

[params.homeInfoParams]
  Title = "Welcome to HamCode!"
  Content = "Where I share my public notes :)"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/hamidhaghdoost"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/hamid-haghdoost"

[[params.socialIcons]]
  name = "stackoverflow"
  url = "https://stackoverflow.com/users/3361796/hamid-haghdoost"

[[params.socialIcons]]
  name = "email"
  url = "mailto:hamidcs92@gmail.com"

[params.label]
  text = "HamCode"
  icon = "/favicon.ico"
  iconHeight = 35

[params.cover]
  linkFullImages = true
  responsiveImages = true

[params.editPost]
  URL = "https://github.com/hamcodenet/hamcodenet.github.io/tree/master/content"
  Text = "Suggest Changes"
  appendFilePath = true

[[menu.main]]
  name = "Mentorship"
  url = "/mentorship/"
  weight = 1

[[menu.main]]
  name = "About me"
  url = "/about/"
  weight = 2
